options(stringsAsFactors = FALSE)
library(data.table)
library(ggplot2)
library(lubridate)
library(reshape2)
library(zoo)

colnames <- c('index','percent_change')
house_price_index <- data.table(read.table("/Users/james/development/resources/nz-houses/data/math/house_price_index_start_1963Q2.txt", header = FALSE, sep="\t", col.names=colnames))
house_price_index$date <- as.Date(seq(as.yearqtr("196305", "%Y%m"), length.out=200, by=1/4))

house_price_index_ts <- read.zoo(house_price_index, index = 3)
house_price_index_ts_since_2000 <- window(house_price_index_ts, start = as.Date("2000-01-01"), end = as.Date("2013-09-01"))
house_price_index_ts_since_2009 <- window(house_price_index_ts, start = as.Date("2009-01-01"), end = as.Date("2013-09-01"))

ggplot(house_price_index) + geom_line(aes(x=date,y=index))
autoplot(house_price_index_ts_since_2000$index, facet = NULL)
autoplot(house_price_index_ts$index, facet = NULL)




ggplot(house_price_index_ts[]) + geom_histogram(aes(index),binwidth=0.05)
ggplot(subset(zz,floating.zz >= 0)) + geom_histogram(aes(floating.zz),binwidth=0.05)

nrow(subset(zz,floating.zz>0))
zzdf <- data.table(data.frame(zz))
a <- subset(zzdf,floating.zz >= 0)[, .N, ,by=floating.zz][order(floating.zz)]
a$probability <- a$N/sum(a$N)
b <- subset(zzdf,floating.zz < 0)[, .N, ,by=floating.zz][order(-floating.zz)]
b$probability <- b$N/sum(b$N)
c <- subset(zzdf,floating.zz != 'NA')[, .N, ,by=floating.zz][order(floating.zz)]
c$probability <- c$N/sum(c$N)

write.table(a,"/Users/james/development/resources/nz-houses/data/math/interest_rate_walk_probabilities.txt", row.names=FALSE, col.names=FALSE,na="-99",sep="\t")



# ================ interest generated by python random walk script =================

interest_generated <- data.table(read.table("/Users/james/development/resources/nz-houses/data/math/interest_rate_array.txt", header = FALSE))
interest_generated$date <- seq(as.Date("2014-01-01"), length.out=360, by="1 month")
ggplot(interest_generated) + geom_line(aes(x=date,y=V1))
























#as.POSIXct(paste("01-", x, sep = ""), format = "%d-%b-%y")
#z <- read.zoo("/Users/james/development/resources/nz-houses/data/mortgage_rates_historical.csv", sep = '\t', format = "%d-%b-%Y")
