options(stringsAsFactors = FALSE)
library(data.table)
library(ggplot2)
library(lubridate)
library(reshape2)
library(zoo)

# ====================== load historical interest rates ========================

colnames <- c('date','floating','twoyrfixed')
interest <- data.table(read.table("/Users/james/development/resources/nz-houses/data/math/mortgage_rates_historical.csv", header = FALSE, sep="\t", col.names=colnames))
interest$date <- dmy(paste("01-", interest$date , sep ="")) 

interest_long <- melt(interest, id="date")
ggplot(interest_long) + geom_line(aes(x=date,y=value,color=variable))

z <- read.zoo(interest)
zz <- diff(z)
zz <- cbind(z,zz)

ggplot(zz) + geom_histogram(aes(floating.zz),binwidth=0.05)
ggplot(subset(zz,floating.zz >= 0)) + geom_histogram(aes(floating.zz),binwidth=0.05)

nrow(subset(zz,floating.zz>0))
zzdf <- data.table(data.frame(zz))
a <- subset(zzdf,floating.zz >= 0)[, .N, ,by=floating.zz][order(floating.zz)]
a$probability <- a$N/sum(a$N)
b <- subset(zzdf,floating.zz < 0)[, .N, ,by=floating.zz][order(-floating.zz)]
b$probability <- b$N/sum(b$N)
c <- subset(zzdf,floating.zz != 'NA')[, .N, ,by=floating.zz][order(floating.zz)]
c$probability <- c$N/sum(c$N)

write.table(a,"/Users/james/development/resources/nz-houses/data/math/interest_rate_walk_probabilities.txt", row.names=FALSE, col.names=FALSE,na="-99",sep="\t")



# ================ interest generated by python random walk script =================

interest_generated <- data.table(read.table("/Users/james/development/resources/nz-houses/data/math/interest_rate_array.txt", header = FALSE))
interest_generated$date <- seq(as.Date("2014-01-01"), length.out=360, by="1 month")
ggplot(interest_generated) + geom_line(aes(x=date,y=V1))






as.Date(seq(as.yearqtr("196305", "%Y%m"), length.out=10, by=1/4))

















#as.POSIXct(paste("01-", x, sep = ""), format = "%d-%b-%y")
#z <- read.zoo("/Users/james/development/resources/nz-houses/data/mortgage_rates_historical.csv", sep = '\t', format = "%d-%b-%Y")
